# server 配置
server:
  servlet:
    context-path: /
  port: 1004
  tomcat:
    uri-encoding: UTF-8
    # 加大tomcat最大连接数, 这里给400
    accept-count: 500
    max-connections: 500
    threads:
      max: 500

spring:
  application:
    name: datasource

logging:
  level:
    com.maruko.mapper: DEBUG